TypeError: BaseGraphModel.get_components() got an unexpected keyword argument 'substation_nodes' (#85)
* Add files via upload

Signed-off-by: Mehmet Keçeci <WhiteSymmetry@users.noreply.github.com>

* Update model_interface.ipynb

Signed-off-by: Mehmet Keçeci <WhiteSymmetry@users.noreply.github.com>

* chore: remove duplicate

Signed-off-by: Jaap Schouten <58551444+jaapschoutenalliander@users.noreply.github.com>

* chore: remove obsolete variable

Signed-off-by: Jaap Schouten <58551444+jaapschoutenalliander@users.noreply.github.com>

* Use new tmp_remove_nodes

Use tmp_remove_nodes instead of the old substation_nodes argument

Signed-off-by: Vincent Koppen <53343926+vincentkoppen@users.noreply.github.com>

---------

Signed-off-by: Mehmet Keçeci <WhiteSymmetry@users.noreply.github.com>
Signed-off-by: Jaap Schouten <58551444+jaapschoutenalliander@users.noreply.github.com>
Signed-off-by: Vincent Koppen <53343926+vincentkoppen@users.noreply.github.com>
Co-authored-by: Jaap Schouten <58551444+jaapschoutenalliander@users.noreply.github.com>
Co-authored-by: Vincent Koppen <53343926+vincentkoppen@users.noreply.github.com>